const WORLD_LORE = `
LUMENWAKE is a drowned observatory-city suspended above a black inland sea. The sun vanished 113 years ago. Citizens survive under a permanent violet twilight generated by the Solar Lens. The player's brass lantern can make remembered events physically real, but every use erases a different memory.

Recurring characters:
- Warden Ilyra: disciplined, protective, afraid that truth will destroy the city.
- Venn, the Moth Archivist: playful, unsettling, values truth over safety.
- The Choir Below: voices inside the sea that may be dead citizens or the city dreaming.

Tone: mysterious, adventurous, emotionally clear, never purple or rambling. Keep each beat compact enough to read while playing.
`;

const ACTIONS = {
  begin: {
    phase: 1,
    speaker: 'The Lantern',
    narration:
      'You wake on a stone jetty while the sea hangs above you like a second sky. Your lantern burns with a memory you do not recognise.',
    dialogue: 'Find the observatory before the tide remembers your name.',
    objective: 'Cross the causeway to the drowned observatory.',
    effects: [
      { type: 'setPhase', value: 1 },
      { type: 'setFlag', key: 'awakened', value: true },
      { type: 'skyMood', value: 'twilight' },
    ],
  },
  approach_observatory: {
    phase: 2,
    speaker: 'The Choir Below',
    narration:
      'The observatory doors breathe open. Inside, an ember floats above a cracked map of a sun that no longer exists.',
    dialogue: 'Take it, little light. We have been cold for a century.',
    objective: 'Recover the ember shard inside the observatory.',
    effects: [
      { type: 'setPhase', value: 2 },
      { type: 'setFlag', key: 'observatoryOpen', value: true },
      { type: 'skyMood', value: 'storm' },
    ],
  },
  take_ember: {
    phase: 3,
    speaker: 'Warden Ilyra',
    narration:
      'The ember folds into your lantern. Every window in the city flashes with the same forgotten sunrise.',
    dialogue: 'Do not move. That light belongs in the Solar Lens, and you have no idea what it remembers.',
    objective: 'Speak with Warden Ilyra.',
    effects: [
      { type: 'setPhase', value: 3 },
      { type: 'addItem', value: 'Ember Shard' },
      { type: 'setFlag', key: 'emberTaken', value: true },
    ],
  },
  talk_warden: {
    phase: 3,
    speaker: 'Warden Ilyra',
    narration:
      'Ilyra lowers her spear, but not enough to make the gesture kind. Moths gather behind her visor whenever she lies.',
    dialogue: 'Give me the ember and I can keep Lumenwake alive. Hide it, and the archive will smell it on you.',
    objective: 'Decide who should control the ember.',
    choices: [
      {
        id: 'choice_trust_warden',
        label: 'Place the ember in Ilyra’s gauntlet',
        hint: 'Trust order over forbidden truth.',
      },
      {
        id: 'choice_seek_archivist',
        label: 'Hide it and ask about the archive',
        hint: 'Risk the city to learn what was erased.',
      },
    ],
    effects: [{ type: 'setFlag', key: 'metWarden', value: true }],
  },
  choice_trust_warden: {
    phase: 4,
    speaker: 'Warden Ilyra',
    narration:
      'Ilyra closes her gauntlet around the ember. Your lantern stays lit anyway. For the first time, she looks frightened of you rather than for you.',
    dialogue: 'The lantern copied it. That should be impossible. Come. We open the archive together.',
    objective: 'Follow the opened stair into the forbidden archive.',
    effects: [
      { type: 'setPhase', value: 4 },
      { type: 'removeItem', value: 'Ember Shard' },
      { type: 'addItem', value: 'Echo of the Ember' },
      { type: 'relationship', key: 'warden', delta: 2 },
      { type: 'relationship', key: 'archivist', delta: -1 },
      { type: 'setFlag', key: 'trustedWarden', value: true },
      { type: 'setFlag', key: 'archiveGateOpen', value: true },
      { type: 'skyMood', value: 'calm' },
    ],
  },
  choice_seek_archivist: {
    phase: 4,
    speaker: 'Venn, the Moth Archivist',
    narration:
      'You cup the ember behind the lantern glass. A white moth lands on your thumb and speaks with a smiling human voice.',
    dialogue: 'Excellent lie. Terrible hiding place. The archive door likes thieves. Let us introduce you.',
    objective: 'Enter the forbidden archive before Ilyra stops you.',
    effects: [
      { type: 'setPhase', value: 4 },
      { type: 'relationship', key: 'warden', delta: -2 },
      { type: 'relationship', key: 'archivist', delta: 2 },
      { type: 'setFlag', key: 'sidedWithArchivist', value: true },
      { type: 'setFlag', key: 'archiveGateOpen', value: true },
      { type: 'skyMood', value: 'moths' },
    ],
  },
  enter_archive: {
    phase: 5,
    speaker: 'The Archive',
    narration:
      'The stair descends through shelves carved into the city’s foundations. Books whisper events that have not happened yet.',
    dialogue: 'One memory may be returned. One must be taken. Choose what kind of person reaches the Lens.',
    objective: 'Touch the memory pool at the archive’s centre.',
    effects: [
      { type: 'setPhase', value: 5 },
      { type: 'setFlag', key: 'insideArchive', value: true },
      { type: 'skyMood', value: 'archive' },
    ],
  },
  touch_memory_pool: {
    phase: 5,
    speaker: 'Venn, the Moth Archivist',
    narration:
      'The pool shows two memories. In one, someone calls your true name. In the other, a stranger watches the old sun being murdered.',
    dialogue: 'Identity or evidence. Comfort or leverage. The pool is not generous enough to offer both.',
    objective: 'Choose which memory to carry.',
    choices: [
      {
        id: 'choice_remember_name',
        label: 'Remember your true name',
        hint: 'Gain resolve, but lose proof of the conspiracy.',
      },
      {
        id: 'choice_steal_memory',
        label: 'Take the stranger’s memory',
        hint: 'Learn who killed the sun, but surrender part of yourself.',
      },
    ],
    effects: [{ type: 'setFlag', key: 'poolAwake', value: true }],
  },
  choice_remember_name: {
    phase: 6,
    speaker: 'The Lantern',
    narration:
      'Your name returns like a hand closing around yours. The city cannot rewrite you as easily now.',
    dialogue: 'You are Elian Vale. You came here once before. You chose to forget.',
    objective: 'Climb to the Solar Lens at the top of the archive.',
    effects: [
      { type: 'setPhase', value: 6 },
      { type: 'addItem', value: 'True Name' },
      { type: 'setFlag', key: 'rememberedName', value: true },
      { type: 'heal', value: 15 },
      { type: 'setFlag', key: 'lensPathOpen', value: true },
    ],
  },
  choice_steal_memory: {
    phase: 6,
    speaker: 'The Choir Below',
    narration:
      'You inherit the last sight of the old sun: Warden Ilyra’s predecessors chained it beneath the sea to power the city forever.',
    dialogue: 'Now you know why every Warden fears dawn.',
    objective: 'Climb to the Solar Lens with the stolen truth.',
    effects: [
      { type: 'setPhase', value: 6 },
      { type: 'addItem', value: 'Stolen Sunrise' },
      { type: 'setFlag', key: 'knowsConspiracy', value: true },
      { type: 'damage', value: 20 },
      { type: 'relationship', key: 'archivist', delta: 1 },
      { type: 'setFlag', key: 'lensPathOpen', value: true },
    ],
  },
  reach_solar_lens: {
    phase: 7,
    speaker: 'The Solar Lens',
    narration:
      'The Lens unfolds above the sea. Inside it, the captive sun beats like a heart. Ilyra and Venn wait on opposite sides of the mechanism.',
    dialogue: 'Restore what was stolen, preserve the city’s twilight, or break the machine and let the sea decide.',
    objective: 'Choose the fate of Lumenwake.',
    choices: [
      {
        id: 'final_restore_dawn',
        label: 'Release the sun and restore dawn',
        hint: 'Save the truth, risk the city built on darkness.',
      },
      {
        id: 'final_keep_twilight',
        label: 'Bind the ember and preserve twilight',
        hint: 'Protect the city, continue its oldest lie.',
      },
      {
        id: 'final_break_lantern',
        label: 'Shatter the lantern into the Lens',
        hint: 'Reject both plans and gamble everything.',
      },
    ],
    effects: [
      { type: 'setPhase', value: 7 },
      { type: 'setFlag', key: 'atLens', value: true },
      { type: 'skyMood', value: 'lens' },
    ],
  },
};

function endingFor(action, state) {
  const trustedWarden = Boolean(state?.flags?.trustedWarden);
  const knowsConspiracy = Boolean(state?.flags?.knowsConspiracy);
  const rememberedName = Boolean(state?.flags?.rememberedName);

  if (action === 'final_restore_dawn') {
    return {
      phase: 8,
      speaker: knowsConspiracy ? 'Elian Vale' : 'The Lantern',
      narration: knowsConspiracy
        ? 'You speak the names of the people who chained the sun, then open the Lens. Daylight tears through every false wall in Lumenwake. Some towers fall. More doors open.'
        : 'You open the Lens without knowing every consequence. Dawn floods the drowned city, revealing gardens beneath the black water and roads that were hidden by fear.',
      dialogue: rememberedName
        ? 'The first sunrise remembers you back.'
        : 'You lose your name in the light, but the city keeps it for you.',
      objective: 'Ending reached: The Honest Dawn',
      ending: {
        result: 'win',
        title: 'THE HONEST DAWN',
        text: trustedWarden
          ? 'Ilyra survives and becomes the first Warden elected in daylight.'
          : 'Venn scatters the archive across the city so no one can erase the truth again.',
      },
      effects: [
        { type: 'setPhase', value: 8 },
        { type: 'skyMood', value: 'dawn' },
        { type: 'ending', value: 'honest-dawn' },
      ],
    };
  }

  if (action === 'final_keep_twilight') {
    return {
      phase: 8,
      speaker: trustedWarden ? 'Warden Ilyra' : 'Venn, the Moth Archivist',
      narration:
        'You bind the ember into the Lens. The city steadies. Twilight becomes warmer, gentler, and yours to govern, but the captive sun still knocks beneath the sea.',
      dialogue: trustedWarden
        ? 'We saved everyone alive today. Tomorrow, we decide what honesty costs.'
        : 'A beautiful compromise. Those are usually the most dangerous kind.',
      objective: 'Ending reached: The Gentle Lie',
      ending: {
        result: 'win',
        title: 'THE GENTLE LIE',
        text: knowsConspiracy
          ? 'You keep the evidence and become the city’s uneasy conscience.'
          : 'You become Keeper of the Lens, protecting a peace built on an unanswered question.',
      },
      effects: [
        { type: 'setPhase', value: 8 },
        { type: 'skyMood', value: 'goldTwilight' },
        { type: 'ending', value: 'gentle-lie' },
      ],
    };
  }

  return {
    phase: 8,
    speaker: 'The Choir Below',
    narration:
      'You shatter the lantern. Every stolen memory escapes at once. The Lens cracks, the sea rises, and Lumenwake becomes a thousand glowing stories with no city left to hold them.',
    dialogue: rememberedName
      ? 'Elian Vale, remembered at the end.'
      : 'A hero without a name is still a hero. The sea is simply bad at monuments.',
    objective: 'Ending reached: The Beautiful Ruin',
    ending: {
      result: 'lose',
      title: 'THE BEAUTIFUL RUIN',
      text: 'The city is lost, but its memories spread across the world as living lights.',
    },
    effects: [
      { type: 'setPhase', value: 8 },
      { type: 'damage', value: 100 },
      { type: 'skyMood', value: 'ruin' },
      { type: 'ending', value: 'beautiful-ruin' },
    ],
  };
}

export function getCanonicalBeat(action, state = {}) {
  if (action.startsWith('final_')) return endingFor(action, state);
  return ACTIONS[action] ?? {
    phase: state.phase ?? 1,
    speaker: 'The Lantern',
    narration: 'The lantern repeats the moment with a slightly different shadow, but the path ahead remains unchanged.',
    dialogue: 'You have already taken what this place can give.',
    objective: state.objective ?? 'Continue exploring Lumenwake.',
    effects: [],
  };
}

export function buildSystemPrompt(canonicalBeat) {
  return `${WORLD_LORE}
You are the live narrative director for a first-person 3D game. React specifically to the supplied player state and action. Vary imagery, dialogue, and emotional consequences between playthroughs, but preserve the canonical gameplay progression supplied below.

CANONICAL GAMEPLAY BEAT (must remain mechanically compatible):
${JSON.stringify(canonicalBeat)}

Return exactly this protocol and nothing else:
<story>One compact paragraph of immediate narration, 35-80 words.</story>
<state>{"speaker":"name","dialogue":"1-3 short sentences","objective":"short objective","summary":"one sentence compact memory","ambient":"twilight|storm|calm|moths|archive|lens|dawn|goldTwilight|ruin"}</state>

Rules:
- Do not add choices; the game supplies canonical choices.
- Do not invent mechanics or items that the client cannot represent.
- Never mention prompts, APIs, models, JSON, or being an AI.
- Keep dialogue readable during play.
- Make the beat acknowledge inventory, relationships, and prior flags when relevant.`;
}

export function compactState(state = {}) {
  return {
    phase: Number(state.phase ?? 0),
    health: Number(state.health ?? 100),
    location: String(state.location ?? 'jetty').slice(0, 80),
    inventory: Array.isArray(state.inventory) ? state.inventory.slice(0, 8) : [],
    relationships: state.relationships ?? { warden: 0, archivist: 0 },
    flags: Object.fromEntries(Object.entries(state.flags ?? {}).slice(0, 20)),
    summary: String(state.summary ?? '').slice(0, 900),
    recentBeats: Array.isArray(state.recentBeats)
      ? state.recentBeats.slice(-3).map((beat) => String(beat).slice(0, 220))
      : [],
  };
}

export function mergeGeneratedBeat(canonical, generated = {}) {
  const allowedAmbient = new Set([
    'twilight',
    'storm',
    'calm',
    'moths',
    'archive',
    'lens',
    'dawn',
    'goldTwilight',
    'ruin',
  ]);

  const ambient = allowedAmbient.has(generated.ambient) ? generated.ambient : null;
  const effects = [...(canonical.effects ?? [])];
  if (ambient && !effects.some((effect) => effect.type === 'skyMood')) {
    effects.push({ type: 'skyMood', value: ambient });
  }

  return {
    ...canonical,
    narration: cleanText(generated.narration, canonical.narration, 700),
    speaker: cleanText(generated.speaker, canonical.speaker, 80),
    dialogue: cleanText(generated.dialogue, canonical.dialogue, 500),
    objective: cleanText(generated.objective, canonical.objective, 180),
    summary: cleanText(
      generated.summary,
      `${canonical.speaker}: ${canonical.narration}`,
      280,
    ),
    effects,
  };
}

function cleanText(value, fallback, maxLength) {
  if (typeof value !== 'string') return fallback;
  const cleaned = value.replace(/[<>]/g, '').trim();
  return cleaned ? cleaned.slice(0, maxLength) : fallback;
}
